### ISSUE TITLE
WarpDrive is crashing

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/squirrelpak-mc12#72]
`
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [4, 24] @ World_Data (72 128 392) is reloading after only 7654 ms
[09:58:41] [Server thread/INFO] [warpdrive]: java.lang.RuntimeException
[09:58:41] [Server thread/INFO] [warpdrive]:  at cr0s.warpdrive.data.ChunkData.load(ChunkData.java:71)
[09:58:41] [Server thread/INFO] [warpdrive]:  at cr0s.warpdrive.event.ChunkHandler.onLoadChunkData(ChunkHandler.java:110)
[09:58:41] [Server thread/INFO] [warpdrive]:  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1450_ChunkHandler_onLoadChunkData_Load.invoke(.dynamic)
[09:58:41] [Server thread/INFO] [warpdrive]:  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[09:58:41] [Server thread/INFO] [warpdrive]:  at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[09:58:41] [Server thread/INFO] [warpdrive]:  at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:103)
[09:58:41] [Server thread/INFO] [warpdrive]:  at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
[09:58:41] [Server thread/INFO] [warpdrive]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
[09:58:41] [Server thread/INFO] [warpdrive]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[09:58:41] [Server thread/INFO] [warpdrive]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[09:58:41] [Server thread/INFO] [warpdrive]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[09:58:41] [Server thread/INFO] [warpdrive]:  at java.lang.Thread.run(Thread.java:748)
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [12, 24] @ World_Data (200 128 392) is reloading after only 7670 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [3, 24] @ World_Data (56 128 392) is reloading after only 7662 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [11, 24] @ World_Data (184 128 392) is reloading after only 7675 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [6, 24] @ World_Data (104 128 392) is reloading after only 7661 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [14, 24] @ World_Data (232 128 392) is reloading after only 7673 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [5, 24] @ World_Data (88 128 392) is reloading after only 7664 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [13, 24] @ World_Data (216 128 392) is reloading after only 7676 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [8, 24] @ World_Data (136 128 392) is reloading after only 7684 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [0, 24] @ World_Data (8 128 392) is reloading after only 7673 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [16, 24] @ World_Data (264 128 392) is reloading after only 7693 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [7, 24] @ World_Data (120 128 392) is reloading after only 7667 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [-1, 24] @ World_Data (-8 128 392) is reloading after only 7678 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [15, 24] @ World_Data (248 128 392) is reloading after only 7680 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [2, 24] @ World_Data (40 128 392) is reloading after only 7676 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [18, 24] @ World_Data (296 128 392) is reloading after only 7694 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [10, 24] @ World_Data (168 128 392) is reloading after only 7690 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [1, 24] @ World_Data (24 128 392) is reloading after only 7681 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [17, 24] @ World_Data (280 128 392) is reloading after only 7699 ms
[09:58:41] [Server thread/WARN] [warpdrive]: Chunk [9, 24] @ World_Data (152 128 392) is reloading after only 7695 ms
> 
`

**Comment by DocCyblade** [comment]
Looks like it could be a bug in the new version. I logged an issue https://github.com/LemADEC/WarpDrive/issues/484

**Comment by DocCyblade** [comment]
Confirmed LemADEC/WarpDrive#484 that it is a bug. Will roll back to older version
